# Generated by Django 4.1.1 on 2022-10-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0002_profilefeeditem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilefeeditem", old_name="create_on", new_name="created_on",
        ),
    ]
