# Generated by Django 4.1.1 on 2022-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0004_alter_userprofile_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
