# Generated by Django 4.1.1 on 2022-11-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plants",
            fields=[
                ("growName", models.CharField(max_length=255, unique=True)),
                (
                    "plantName",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("hydroponics", models.BooleanField()),
                ("sustrate", models.BooleanField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pruning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pruning", models.BooleanField()),
                ("notes", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "pruningPlant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mastergrow_api.plants",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pesticides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pesticides", models.BooleanField()),
                ("notes", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "pesticidePlant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mastergrow_api.plants",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseNutrients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Macronutrients", models.IntegerField()),
                ("Micronutrients", models.IntegerField()),
                ("silicio", models.IntegerField()),
                ("mycorrhizae", models.IntegerField()),
                ("trichodermas", models.IntegerField()),
                ("rootBiostimulant", models.IntegerField()),
                ("notes", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "plantGrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mastergrow_api.plants",
                    ),
                ),
            ],
        ),
    ]
