# Generated by Django 4.1.1 on 2022-11-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mastergrow_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantsDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.BooleanField()),
                ("notes", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "plantsDisease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mastergrow_api.plants",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PruningPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pruning", models.BooleanField()),
                ("notes", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "Plantpruning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mastergrow_api.plants",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="pesticides",
            old_name="pesticidePlant",
            new_name="plantPesticide",
        ),
        migrations.DeleteModel(name="Pruning",),
    ]
