# Generated by Django 4.1.1 on 2022-11-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastergrow_api", "0002_plantsdisease_pruningplant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basenutrients",
            name="BloomFlowering",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basenutrients",
            name="Macronutrients",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basenutrients",
            name="Micronutrients",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basenutrients",
            name="mycorrhizae",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basenutrients",
            name="rootBiostimulant",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basenutrients",
            name="silicio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basenutrients",
            name="trichodermas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pesticides",
            name="pesticides",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="plantsdisease",
            name="disease",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pruningplant",
            name="pruning",
            field=models.BooleanField(default=False),
        ),
    ]
